export const CANDIDATE_LOGIN_REQUEST = 'CANDIDATE_LOGIN_REQUEST'
export const CANDIDATE_LOGIN_SUCCESS = 'CANDIDATE_LOGIN_SUCCESS'
export const CANDIDATE_LOGIN_FAIL = 'CANDIDATE_LOGIN_FAIL'

export const CANDIDATE_LOGOUT = 'CANDIDATE_LOGOUT'