# Generated by Django 3.2.18 on 2023-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
